epafdv:
  jarPath: target/externalJars
  configDir: /bin/epa-modul/config
  isStarted: true
epaps:
  jarPath: target/externalJars
  isStarted: false
ncpeh:
  jarPath: target/externalJars
  isStarted: false
  inDocker: false
  
management:
  endpoints:
    web:
      exposure:
        include: info
        
  info:
    env:
      enabled: true

info:
  application:
    name: ${spring.application.name}
    description: Very cool Spring Boot application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
